package com.arkansashome.mortgage;

import android.app.*;
import android.os.Bundle;
import android.content.*;
import android.graphics.Color;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, content; TextView title, step; int page=0; final int PAGES=7;
    android.content.SharedPreferences prefs;
    final int TEAL=Color.rgb(0,135,179), RED=Color.rgb(201,0,59), DARK=Color.rgb(23,49,59), LIGHT=Color.rgb(242,248,252);
    final String[] titles={"Borrower Information","Employment & Income","Assets & Liabilities","Property & Loan","Declarations","Demographics","Review & Submit"};
    final Map<String,String> data=new LinkedHashMap<>();
    @Override public void onCreate(Bundle b){super.onCreate(b); prefs=getSharedPreferences("application",0); load(); showWelcome();}
    TextView tv(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(DARK);v.setPadding(0,8,0,8);return v;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundColor(TEAL);b.setPadding(18,10,18,10);return b;}
    EditText field(String key,String hint,boolean money){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setPadding(16,12,16,12);e.setTag(key);if(money)e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); else e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);String val=data.get(key);if(val!=null)e.setText(val);content.addView(e,new LinearLayout.LayoutParams(-1,ViewGroup.LayoutParams.WRAP_CONTENT));return e;}
    void base(String heading){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);root.setPadding(28,18,28,20);setContentView(root);
        ImageView mark=new ImageView(this);mark.setImageResource(com.arkansashome.mortgage.R.drawable.ahm_mark);mark.setAdjustViewBounds(true);root.addView(mark,new LinearLayout.LayoutParams(-1,100));
        title=tv(heading,25);title.setTextColor(TEAL);root.addView(title);step=tv("Step "+(page+1)+" of "+PAGES,13);step.setTextColor(Color.GRAY);root.addView(step);
        ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(0,8,0,10);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout nav=new LinearLayout(this);nav.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("Back"), next=btn(page==PAGES-1?"Finish":"Continue");nav.addView(back,new LinearLayout.LayoutParams(0,56,1));Space sp=new Space(this);nav.addView(sp,new LinearLayout.LayoutParams(12,56));nav.addView(next,new LinearLayout.LayoutParams(0,56,1));root.addView(nav);
        back.setOnClickListener(v->{saveFields();if(page>0){page--;showPage();}else showWelcome();}); next.setOnClickListener(v->{saveFields();if(page<PAGES-1){page++;showPage();}else finishApplication();});
    }
    void showWelcome(){page=0;root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(30,28,30,24);root.setBackgroundColor(LIGHT);setContentView(root);
        ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.ahm_logo);logo.setAdjustViewBounds(true);root.addView(logo,new LinearLayout.LayoutParams(-1,0,1));
        TextView h=tv("Apply For Your Home Loan",25);h.setTextColor(TEAL);h.setGravity(Gravity.CENTER);root.addView(h);
        TextView sub=tv("Residential mortgage application",16);sub.setGravity(Gravity.CENTER);root.addView(sub);
        TextView n=tv("Arkansas Home Mortgage NMLS ID 2560263\nMark Wilson NMLS# 641232",13);n.setGravity(Gravity.CENTER);n.setPadding(0,18,0,18);root.addView(n);
        Button start=btn(data.isEmpty()?"Start New Application":"Continue Application");root.addView(start,new LinearLayout.LayoutParams(-1,60));start.setOnClickListener(v->showPage());
    }
    void showPage(){base(titles[page]);switch(page){case 0: borrower();break;case 1: income();break;case 2: assets();break;case 3: property();break;case 4: declarations();break;case 5: demographics();break;case 6: review();}}
    void label(String s){TextView l=tv(s,16);l.setTextColor(DARK);l.setPadding(0,14,0,4);content.addView(l);}
    void borrower(){label("Applicant");field("first","First name",false);field("middle","Middle name",false);field("last","Last name",false);field("suffix","Suffix",false);field("dob","Date of birth (MM/DD/YYYY)",false);field("ssn","Social Security number",false);field("email","Email address",false);field("phone","Phone number",false);label("Current residence");field("address","Street address",false);field("unit","Unit #",false);field("city","City",false);field("state","State",false);field("zip","ZIP code",false);field("housing","Housing status (Own / Rent / No Primary Housing Expense)",false);field("monthlyHousing","Monthly housing expense",true);field("dependents","Number of dependents",false);label("Application type");field("creditType","Individual Credit or Joint Credit",false);field("borrowerCount","Total number of borrowers",false);}
    void income(){label("Current employment / self-employment");field("employer","Employer or business name",false);field("employerPhone","Employer phone",false);field("position","Position / title",false);field("startDate","Employment start date",false);field("baseIncome","Base monthly income",true);field("overtime","Overtime monthly income",true);field("bonus","Bonus monthly income",true);field("commission","Commission monthly income",true);field("selfIncome","Self-employment monthly income",true);label("Other qualifying income");field("otherIncome","Other monthly qualifying income",true);field("otherIncomeType","Source/type of other income",false);}
    void assets(){label("Financial assets");field("checking","Checking account balance",true);field("savings","Savings account balance",true);field("retirement","Retirement account balance",true);field("stocks","Stocks / bonds / mutual funds",true);field("giftFunds","Gift funds",true);field("otherAssets","Other assets",true);label("Liabilities");field("creditCards","Monthly credit card payments",true);field("autoLoans","Monthly auto loan payments",true);field("studentLoans","Monthly student loan payments",true);field("installment","Other installment payments",true);field("otherDebt","Other monthly obligations",true);field("mortgageDebt","Current mortgage payments",true);}
    void property(){label("Subject property");field("propertyAddress","Property street address",false);field("propertyCity","City",false);field("propertyState","State",false);field("propertyZip","ZIP code",false);field("propertyType","Property type (Single Family / Condo / 2-4 Unit / Other)",false);field("occupancy","Occupancy (Primary / Second Home / Investment)",false);field("units","Number of units",false);label("Loan information");field("purpose","Purpose (Purchase / Refinance / Other)",false);field("purchasePrice","Purchase price / estimated value",true);field("loanAmount","Loan amount",true);field("downPayment","Down payment",true);field("term","Loan term in years",false);field("loanType","Loan type (Conventional / FHA / VA / USDA / Other)",false);}
    void declarations(){label("Declarations");String[] qs={"Will you occupy the property as your primary residence?","Have you had an ownership interest in another property in the last three years?","Have you had a foreclosure, deed-in-lieu, or short sale?","Have you declared bankruptcy within the last seven years?","Are you currently delinquent or in default on a federal debt?","Are there any outstanding judgments against you?","Are you a party to a lawsuit in which you have potential liability?","Have you borrowed money for this transaction that you have not disclosed?"};for(int i=0;i<qs.length;i++){label(qs[i]);field("decl"+i,"Yes / No",false);}}
    void demographics(){label("Government Monitoring Information");field("ethnicity","Ethnicity (optional demographic information)",false);field("race","Race (optional demographic information)",false);field("sex","Sex (optional demographic information)",false);label("Supplemental Consumer Information");field("language","Language preference",false);field("housingCounseling","Housing counseling / homeownership education",false);}
    String money(String k){try{return String.format(java.util.Locale.US,"$%,.2f",Double.parseDouble(data.getOrDefault(k,"0")));}catch(Exception e){return "$0.00";}}
    void review(){label("Application summary");String[] keys={"first","last","email","phone","employer","baseIncome","checking","savings","propertyAddress","propertyCity","propertyState","purpose","purchasePrice","loanAmount","downPayment","term","loanType"};for(String k:keys){if(data.containsKey(k)&&!data.get(k).isEmpty()){String v=data.get(k);if(k.equals("baseIncome")||k.equals("checking")||k.equals("savings")||k.equals("purchasePrice")||k.equals("loanAmount")||k.equals("downPayment"))v=money(k);TextView t=tv(k+": "+v,15);content.addView(t);}}
        double price=num("purchasePrice"), loan=num("loanAmount"); if(price>0&&loan>0){double ltv=loan/price*100;TextView t=tv(String.format(Locale.US,"Estimated LTV: %.2f%%",ltv),18);t.setTextColor(TEAL);content.addView(t);}TextView note=tv("Review all information carefully before submitting. This version saves the application locally on this device and does not transmit borrower data to a lender or credit bureau.",13);note.setPadding(0,20,0,10);content.addView(note);}
    double num(String k){try{return Double.parseDouble(data.getOrDefault(k,"0"));}catch(Exception e){return 0;}}
    void saveFields(){if(content==null)return;for(int i=0;i<content.getChildCount();i++){View v=content.getChildAt(i);if(v instanceof EditText){String k=(String)v.getTag();if(k!=null)data.put(k,((EditText)v).getText().toString());}}SharedPreferences.Editor e=prefs.edit();for(Map.Entry<String,String>x:data.entrySet())e.putString(x.getKey(),x.getValue());e.apply();}
    void load(){for(Map.Entry<String,?> x:prefs.getAll().entrySet())data.put(x.getKey(),String.valueOf(x.getValue()));}
    void finishApplication(){saveFields();new AlertDialog.Builder(this).setTitle("Application Saved").setMessage("Your Arkansas Home Mortgage application has been saved on this device.\n\nA production release should add encrypted cloud storage, identity verification, e-signature, disclosure delivery, LOS integration, and secure lender submission before use with live borrower data.").setPositiveButton("Done",(d,w)->showWelcome()).show();}
}
